{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "erp-platform.serviceAccountName" . }}
  labels:
    {{- include "erp-platform.labels" . | nindent 4 }}
{{- end }}
