"""Classification enums and result models."""

from __future__ import annotations

from enum import StrEnum


class PrimaryClassification(StrEnum):
    NO_PROXY = "NO_PROXY"
    DEAD_PROXY_CONFIG = "DEAD_PROXY_CONFIG"
    LOCAL_PROXY_ACTIVE = "LOCAL_PROXY_ACTIVE"
    UNKNOWN_LOCAL_PROXY = "UNKNOWN_LOCAL_PROXY"
    KNOWN_DEV_PROXY = "KNOWN_DEV_PROXY"
    KNOWN_SECURITY_TOOL = "KNOWN_SECURITY_TOOL"
    SUSPICIOUS_PROXY = "SUSPICIOUS_PROXY"
    POSSIBLE_MITM_RISK = "POSSIBLE_MITM_RISK"
    PAC_CONFIGURED = "PAC_CONFIGURED"
    WININET_WINHTTP_MISMATCH = "WININET_WINHTTP_MISMATCH"
    REVERTER_SUSPECTED = "REVERTER_SUSPECTED"
    ERROR_INSUFFICIENT_DATA = "ERROR_INSUFFICIENT_DATA"


class SecondarySignal(StrEnum):
    WININET_WINHTTP_MISMATCH = "WININET_WINHTTP_MISMATCH"
    LOCALHOST_PROXY = "LOCALHOST_PROXY"
    DEAD_LOCALHOST_PORT = "DEAD_LOCALHOST_PORT"
    PAC_PRESENT = "PAC_PRESENT"
    UNKNOWN_LISTENER = "UNKNOWN_LISTENER"
    KNOWN_DEV_TOOL = "KNOWN_DEV_TOOL"
    KNOWN_SECURITY_TOOL = "KNOWN_SECURITY_TOOL"
    REGISTRY_REWRITE_OBSERVED = "REGISTRY_REWRITE_OBSERVED"
    WRITER_LISTENER_MISMATCH = "WRITER_LISTENER_MISMATCH"
    REPEATED_PROXY_REAPPEARANCE = "REPEATED_PROXY_REAPPEARANCE"
    SUSPICIOUS_PROCESS_PATH = "SUSPICIOUS_PROCESS_PATH"
