"""Local-first operability — structured logs, trace context, in-memory Prometheus metrics."""

from src.platform_core.operability.context import (
    correlation_fields,
    get_audit_id,
    get_trace_id,
    new_audit_id,
    new_trace_id,
    observability_scope,
    set_audit_id,
    set_trace_id,
)
from src.platform_core.operability.events import (
    record_agent_heartbeat,
    record_audit_appended,
    record_blocked_action,
    record_control_test_executed,
    record_evidence_collected,
    record_incident_classified,
    record_policy_decision,
    record_remediation_preview,
    update_spool_queue_depth,
)
from src.platform_core.operability.metrics_registry import (
    METRIC_AGENT_HEARTBEAT,
    METRIC_AUDIT_APPENDED,
    METRIC_BLOCKED_ACTIONS,
    METRIC_CONTROL_TESTS_EXECUTED,
    METRIC_EVIDENCE_COLLECTED,
    METRIC_INCIDENTS_CLASSIFIED,
    METRIC_POLICY_DECISIONS,
    METRIC_REMEDIATION_PREVIEWS,
    METRIC_SPOOL_DEPTH,
    get_counter,
    get_gauge,
    inc_counter,
    render_prometheus_text,
    reset_metrics_for_tests,
    set_gauge,
)
from src.platform_core.operability.structured_logging import log_json, structured_logging_enabled

__all__ = [
    "METRIC_AGENT_HEARTBEAT",
    "METRIC_AUDIT_APPENDED",
    "METRIC_BLOCKED_ACTIONS",
    "METRIC_CONTROL_TESTS_EXECUTED",
    "METRIC_EVIDENCE_COLLECTED",
    "METRIC_INCIDENTS_CLASSIFIED",
    "METRIC_POLICY_DECISIONS",
    "METRIC_REMEDIATION_PREVIEWS",
    "METRIC_SPOOL_DEPTH",
    "correlation_fields",
    "get_audit_id",
    "get_counter",
    "get_gauge",
    "get_trace_id",
    "inc_counter",
    "log_json",
    "new_audit_id",
    "new_trace_id",
    "observability_scope",
    "record_agent_heartbeat",
    "record_audit_appended",
    "record_blocked_action",
    "record_control_test_executed",
    "record_evidence_collected",
    "record_incident_classified",
    "record_policy_decision",
    "record_remediation_preview",
    "render_prometheus_text",
    "reset_metrics_for_tests",
    "set_audit_id",
    "set_gauge",
    "set_trace_id",
    "structured_logging_enabled",
    "update_spool_queue_depth",
]
