#!/usr/bin/env python3
"""OpenClaw task runner — policy gate, validation stages, draft-PR workflow helpers.

This script does **not** invoke OpenClaw model inference itself. It:
  1. Loads an approved task (local JSON or GitHub issue labeled agent-ready)
  2. Evaluates task policy (BLOCK high/critical, secrets, live remediation, etc.)
  3. Creates/checks an isolated agent/openclaw/* branch
  4. Runs staged validation (targeted then optional full)
  5. Optionally creates a **draft** pull request via ``gh``
  6. Writes a local audit JSON (gitignored runtime dir)

It never merges PRs, deploys, or executes live Windows remediation.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from src.platform_core.openclaw import (  # noqa: E402
    evaluate_task_policy,
    expected_branch_name,
    new_run_audit,
    task_from_mapping,
    validate_changed_paths,
    write_run_audit,
)
from src.platform_core.openclaw.models import OpenClawTask  # noqa: E402

DEFAULT_AUDIT_DIR = _REPO_ROOT / ".openclaw" / "runs"
DEFAULT_MAX_FILES = 20
DEFAULT_MAX_LINES = 1500

PR_BODY_TEMPLATE = """## Summary

{summary}

## Approved task

- Task ID: `{task_id}`
- Title: {title}
- Risk level: `{risk_level}`

## Changed files

{changed_files}

## Validation performed

{validation}

## Test results

{test_results}

## Security and compatibility risks

{risks}

## Known limitations

- OpenClaw generates candidate changes. Passing tests does not prove that the code is free of defects or safe for production.
- Policy permission is not a safety guarantee.
- Dry-run / preview-only remediation defaults are unchanged by this automation.

## Rollback plan

{rollback}

## Human review required

This pull request was generated by an automated coding agent.
It must not be merged without human review and required CI checks.
"""


def _run(
    argv: Sequence[str],
    *,
    cwd: Path,
    timeout: int = 600,
    check: bool = False,
) -> subprocess.CompletedProcess[str]:
    """Run a command as an argument list (never shell=True)."""
    return subprocess.run(
        list(argv),
        cwd=str(cwd),
        capture_output=True,
        text=True,
        timeout=timeout,
        shell=False,
        check=check,
    )


def load_task_from_json(path: Path) -> OpenClawTask:
    raw = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError("task file must be a JSON object")
    return task_from_mapping(raw)


def load_task_from_github_issue(issue_number: str, *, repo: str | None = None) -> OpenClawTask:
    """Load issue via ``gh`` CLI — requires label agent-ready and explicit approval marker."""
    argv = ["gh", "issue", "view", str(issue_number), "--json", "number,title,body,labels"]
    if repo:
        argv.extend(["--repo", repo])
    proc = _run(argv, cwd=_REPO_ROOT, timeout=60)
    if proc.returncode != 0:
        raise RuntimeError(f"gh issue view failed: {proc.stderr.strip()}")
    data = json.loads(proc.stdout)
    labels = [str(x.get("name") or "") for x in (data.get("labels") or [])]
    body = str(data.get("body") or "")
    approved = bool(re.search(r"(?im)^\s*approved\s*:\s*true\s*$", body)) or (
        "agent-approved" in {x.lower() for x in labels}
    )
    risk_match = re.search(r"(?im)^\s*risk_level\s*:\s*(\w+)\s*$", body)
    risk = (risk_match.group(1) if risk_match else "low").lower()
    allowed = re.findall(r"(?im)^\s*allowed_path\s*:\s*(.+)\s*$", body)
    forbidden = re.findall(r"(?im)^\s*forbidden_path\s*:\s*(.+)\s*$", body)
    return task_from_mapping(
        {
            "task_id": str(data.get("number")),
            "title": str(data.get("title") or ""),
            "description": body,
            "approved": approved,
            "risk_level": risk,
            "allowed_paths": [p.strip() for p in allowed] or ["windows_network_toolkit/", "tests/", "docs/"],
            "forbidden_paths": [p.strip() for p in forbidden],
            "labels": labels,
        }
    )


def git_current_branch(cwd: Path) -> str:
    proc = _run(["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=cwd, timeout=30)
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr.strip() or "git rev-parse failed")
    return proc.stdout.strip()


def git_create_branch(cwd: Path, branch: str, *, base: str) -> None:
    # Fetch is optional; create from local base ref
    _run(["git", "checkout", base], cwd=cwd, timeout=60)
    proc = _run(["git", "checkout", "-B", branch], cwd=cwd, timeout=60)
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr.strip() or "failed to create branch")


def git_changed_files(cwd: Path, *, base: str) -> list[str]:
    proc = _run(["git", "diff", "--name-only", f"{base}...HEAD"], cwd=cwd, timeout=60)
    if proc.returncode != 0:
        # Fall back to working tree status
        proc = _run(["git", "status", "--porcelain"], cwd=cwd, timeout=60)
        files: list[str] = []
        for line in proc.stdout.splitlines():
            if len(line) >= 4:
                files.append(line[3:].strip())
        return files
    return [ln.strip() for ln in proc.stdout.splitlines() if ln.strip()]


def git_changed_line_count(cwd: Path, *, base: str) -> int:
    proc = _run(["git", "diff", "--numstat", f"{base}...HEAD"], cwd=cwd, timeout=60)
    if proc.returncode != 0:
        return 0
    total = 0
    for line in proc.stdout.splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[0].isdigit() and parts[1].isdigit():
            total += int(parts[0]) + int(parts[1])
    return total


def run_validation_stage1(cwd: Path, paths: list[str]) -> list[dict[str, Any]]:
    results: list[dict[str, Any]] = []
    targets = paths or ["."]
    # Cap argv length — use unique top-level roots
    roots = sorted({p.split("/")[0] for p in targets if p})
    check_paths = roots if roots else ["."]

    for label, argv in (
        ("ruff_check", ["ruff", "check", *check_paths]),
        ("ruff_format", ["ruff", "format", "--check", *check_paths]),
    ):
        proc = _run(argv, cwd=cwd, timeout=300)
        results.append(
            {
                "name": label,
                "ok": proc.returncode == 0,
                "returncode": proc.returncode,
                "stdout_tail": (proc.stdout or "")[-2000:],
                "stderr_tail": (proc.stderr or "")[-2000:],
            }
        )

    # Prefer safety contract + any tests/ paths touched
    test_targets = [p for p in targets if p.startswith("tests/") and p.endswith(".py")]
    if not test_targets:
        test_targets = ["tests/test_policy_safety_contract.py", "tests/test_openclaw_task_policy.py"]
    pytest_argv = [sys.executable, "-m", "pytest", "-q", *test_targets, "--basetemp=.pytest_tmp"]
    proc = _run(pytest_argv, cwd=cwd, timeout=900)
    results.append(
        {
            "name": "pytest_targeted",
            "ok": proc.returncode == 0,
            "returncode": proc.returncode,
            "stdout_tail": (proc.stdout or "")[-3000:],
            "stderr_tail": (proc.stderr or "")[-2000:],
        }
    )
    return results


def run_validation_stage2(cwd: Path) -> list[dict[str, Any]]:
    results: list[dict[str, Any]] = []
    commands: list[tuple[str, list[str]]] = [
        ("ruff_check_all", ["ruff", "check", "."]),
        ("ruff_format_all", ["ruff", "format", "--check", "."]),
        (
            "mypy_scoped",
            [
                "mypy",
                "src/platform_core/ai_risk_analyst",
                "src/platform_core/risk",
                "src/platform_core/governance",
                "src/platform_core/analytics",
                "--ignore-missing-imports",
            ],
        ),
        ("bandit", ["bandit", "-r", "windows_network_toolkit", "src/platform_core", "-q"]),
        ("pytest_all", [sys.executable, "-m", "pytest", "-q", "--basetemp=.pytest_tmp"]),
    ]
    for name, argv in commands:
        proc = _run(argv, cwd=cwd, timeout=1800)
        results.append(
            {
                "name": name,
                "ok": proc.returncode == 0,
                "returncode": proc.returncode,
                "stdout_tail": (proc.stdout or "")[-2000:],
                "stderr_tail": (proc.stderr or "")[-2000:],
            }
        )
        if not results[-1]["ok"] and name in {"ruff_check_all", "pytest_all"}:
            break
    return results


def create_draft_pr(
    cwd: Path,
    *,
    title: str,
    body: str,
    base: str,
) -> str | None:
    proc = _run(
        [
            "gh",
            "pr",
            "create",
            "--draft",
            "--title",
            title,
            "--body",
            body,
            "--base",
            base,
        ],
        cwd=cwd,
        timeout=120,
    )
    if proc.returncode != 0:
        return None
    url = (proc.stdout or "").strip().splitlines()
    return url[-1] if url else None


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Policy-gated OpenClaw coding task runner (draft PR only)")
    src = p.add_mutually_exclusive_group(required=True)
    src.add_argument("--task-json", type=Path, help="Path to approved task JSON")
    src.add_argument("--github-issue", help="GitHub issue number with agent-ready label")
    p.add_argument("--repo", default="", help="Optional owner/repo for gh issue view")
    p.add_argument(
        "--default-branch",
        default="Multi_Domain_Decision_Platform",
        help="Repository default branch (never target for agent commits)",
    )
    p.add_argument("--create-branch", action="store_true", help="Create agent/openclaw/* branch from default")
    p.add_argument("--validate", action="store_true", help="Run validation stages")
    p.add_argument("--full-validate", action="store_true", help="Also run stage-2 repository validation")
    p.add_argument("--create-draft-pr", action="store_true", help="Create draft PR after successful validation")
    p.add_argument("--max-files", type=int, default=DEFAULT_MAX_FILES)
    p.add_argument("--max-lines", type=int, default=DEFAULT_MAX_LINES)
    p.add_argument(
        "--audit-dir",
        type=Path,
        default=DEFAULT_AUDIT_DIR,
        help="Local runtime audit directory (gitignored)",
    )
    p.add_argument("--dry-run", action="store_true", help="Policy + plan only; no branch/PR mutations")
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    cwd = _REPO_ROOT

    if args.task_json:
        task = load_task_from_json(args.task_json)
    else:
        task = load_task_from_github_issue(str(args.github_issue), repo=args.repo or None)

    policy = evaluate_task_policy(task, default_branch=args.default_branch)
    branch = expected_branch_name(task)
    audit = new_run_audit(task_id=task.task_id, branch=branch, policy_decision=policy.decision)
    audit.limitations.extend(list(policy.limitations))

    if not policy.allowed:
        audit.finish("policy_blocked")
        path = write_run_audit(audit, args.audit_dir)
        print(json.dumps({"status": "policy_blocked", "reasons": list(policy.reasons), "audit": str(path)}, indent=2))
        return 2

    if args.dry_run:
        audit.finish("completed_local")
        path = write_run_audit(audit, args.audit_dir)
        print(
            json.dumps(
                {
                    "status": "dry_run_ok",
                    "branch": branch,
                    "policy": policy.decision,
                    "audit": str(path),
                    "next": "Run OpenClaw wnrt-coder on the branch, then re-run with --validate --create-draft-pr",
                },
                indent=2,
            )
        )
        return 0

    current = git_current_branch(cwd)
    if current in {"main", "master", args.default_branch}:
        if not args.create_branch:
            print("Refuse to operate on default branch without --create-branch", file=sys.stderr)
            audit.finish("error")
            write_run_audit(audit, args.audit_dir)
            return 3
        git_create_branch(cwd, branch, base=args.default_branch)
        audit.commands_run.append(f"git checkout -B {branch}")
    elif not current.startswith("agent/openclaw/"):
        print(f"Current branch {current!r} is not an agent/openclaw/* branch", file=sys.stderr)
        audit.finish("error")
        write_run_audit(audit, args.audit_dir)
        return 3

    if args.validate:
        changed = git_changed_files(cwd, base=args.default_branch)
        lines = git_changed_line_count(cwd, base=args.default_branch)
        path_policy = validate_changed_paths(
            changed,
            task,
            max_files=args.max_files,
            max_changed_lines=args.max_lines,
            changed_line_count=lines,
        )
        audit.changed_files = changed
        if not path_policy.allowed:
            audit.finish("validation_failed")
            write_run_audit(audit, args.audit_dir)
            print(json.dumps({"status": "path_policy_blocked", "reasons": list(path_policy.reasons)}, indent=2))
            return 4

        stage1 = run_validation_stage1(cwd, changed)
        audit.test_results.extend(stage1)
        audit.commands_run.extend(r["name"] for r in stage1)
        if not all(r["ok"] for r in stage1):
            audit.finish("validation_failed")
            write_run_audit(audit, args.audit_dir)
            print(json.dumps({"status": "stage1_failed", "results": stage1}, indent=2))
            return 5

        if args.full_validate:
            stage2 = run_validation_stage2(cwd)
            audit.test_results.extend(stage2)
            audit.commands_run.extend(r["name"] for r in stage2)
            if not all(r["ok"] for r in stage2):
                audit.finish("validation_failed")
                write_run_audit(audit, args.audit_dir)
                print(json.dumps({"status": "stage2_failed", "results": stage2}, indent=2))
                return 6

    if args.create_draft_pr:
        if not args.validate:
            print("--create-draft-pr requires --validate", file=sys.stderr)
            audit.finish("error")
            write_run_audit(audit, args.audit_dir)
            return 7
        # Push is operator responsibility / OpenClaw session; attempt draft PR from current branch
        body = PR_BODY_TEMPLATE.format(
            summary=task.title,
            task_id=task.task_id,
            title=task.title,
            risk_level=task.risk_level,
            changed_files="\n".join(f"- `{p}`" for p in audit.changed_files) or "- (see branch diff)",
            validation=", ".join(audit.commands_run) or "stage1",
            test_results=json.dumps(
                [{"name": r.get("name"), "ok": r.get("ok")} for r in audit.test_results],
                indent=2,
            ),
            risks="See allowed_paths / forbidden_paths and safety-contract tests.",
            rollback="Revert the draft PR branch or `git reset` to the base branch commit.",
        )
        title = f"[OpenClaw Draft] {task.title}"
        url = create_draft_pr(cwd, title=title, body=body, base=args.default_branch)
        audit.pull_request_url = url
        if not url:
            audit.finish("error")
            write_run_audit(audit, args.audit_dir)
            print(json.dumps({"status": "draft_pr_failed"}, indent=2))
            return 8
        audit.finish("draft_pr_created")
    else:
        audit.finish("completed_local")

    path = write_run_audit(audit, args.audit_dir)
    print(
        json.dumps(
            {
                "status": audit.status,
                "branch": branch,
                "policy": policy.decision,
                "pull_request_url": audit.pull_request_url,
                "audit": str(path),
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
