"""Append-only audit/report writers for layer-aware diagnosis results.

Module responsibility:
    Persist diagnosis payloads to JSONL and markdown artifacts under repository-local ``logs/`` and
    ``reports/`` paths for replay and operator handoff.

System placement:
    Invoked by :func:`failure_system.layer_decision.run_layer_diagnosis` after classification.

Key invariants:
    - JSONL sink appends one object per line (no in-place rewrites).
    - Markdown reports are timestamped and immutable once created.

Audit Notes:
    File-write failures should be treated as critical observability gaps; rerun diagnosis after
    restoring write permissions and confirm artifacts exist in both output directories.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def _repo_root() -> Path:
    """Resolve repository root from current module location."""
    return Path(__file__).resolve().parent.parent


def append_layer_audit(payload: dict[str, Any]) -> Path:
    """Append one diagnosis payload to ``logs/network_layer_audit.jsonl``.

    Args:
        payload: Final diagnosis payload generated by ``layer_decision``.

    Returns:
        Path: Absolute path of the JSONL sink.

    Side effects:
        Creates ``logs/`` when missing and appends one newline-delimited JSON object.

    Idempotency:
        Not idempotent by design; repeated calls append additional evidence rows.
    """
    path = _repo_root() / "logs" / "network_layer_audit.jsonl"
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(payload, ensure_ascii=False) + "\n")
    return path


def write_markdown_report(payload: dict[str, Any]) -> Path:
    """Create timestamped markdown diagnosis report under ``reports/``.

    Args:
        payload: Final diagnosis payload generated by ``layer_decision``.

    Returns:
        Path: Report file path.

    Side effects:
        Creates ``reports/`` when missing and writes one new markdown file.
    """
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    path = _repo_root() / "reports" / f"network_layer_diagnosis_{ts}.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Network Layer Diagnosis",
        "",
        f"- Timestamp: `{payload.get('timestamp')}`",
        f"- Layer: `{payload.get('layer')}`",
        f"- Failure Type: `{payload.get('failure_type')}`",
        f"- Confidence: `{payload.get('confidence_score')}`",
        f"- Evidence Level: `{payload.get('evidence_level')}`",
        "",
        "## Why this layer",
        "",
        f"{payload.get('failure_type')}: selected from observed evidence-weighted signals.",
        "",
        "## Observed Signals",
        "",
    ]
    for x in payload.get("observed_signals", []):
        lines.append(f"- {x}")
    lines.extend(["", "## Hypotheses", ""])
    for x in payload.get("hypotheses", []):
        lines.append(f"- {x}")
    lines.extend(["", "## Recommended Next Test", "", str(payload.get("recommended_next_test", "")), "", "## Repair Preview", ""])
    for x in payload.get("repair_preview", []):
        lines.append(f"- {x}")
    lines.extend(["", "## Attribution Notes", ""])
    for x in payload.get("attribution_notes", []):
        lines.append(f"- {x}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path

