from __future__ import annotations

"""Report serialization utilities for diagnosis artifacts.

This module sits in the serving/persistence stage of the pipeline. It wraps
diagnostic payloads with report metadata and persists them as JSON files for
later retrieval by API/UI clients.

Key invariants:
- Every report includes a UUID `report_id`.
- `generated_at_utc` is emitted in UTC ISO-8601 format.
- File writes target caller-provided directory, created if missing.
"""

import json
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def build_report(payload: dict[str, Any]) -> dict[str, Any]:
    """Create a report envelope around a diagnosis payload.

    Data assumptions:
        - `payload` is JSON-serializable or intentionally close to it.
        - Caller owns payload schema compatibility across versions.

    Output guarantees:
        - Returns a new mapping with `report_id` and `generated_at_utc`.
        - Preserves original payload keys via dictionary unpacking.

    Side effects:
        None.

    Idempotency:
        Not idempotent by design; each call generates a new UUID and timestamp.

    Args:
        payload: Diagnosis payload to enrich with report metadata.

    Returns:
        dict[str, Any]: Report object ready for serialization.

    Raises:
        None.

    Example:
        >>> report = build_report({"diagnosis": []})
        >>> "report_id" in report
        True
    """
    return {
        "report_id": str(uuid.uuid4()),
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        **payload,
    }


def write_report(report: dict[str, Any], reports_dir: Path) -> Path:
    """Persist a report as a UTF-8 JSON file.

    Schema expectations:
        - `report` contains a string `report_id` key.
        - `report` values are JSON-serializable.

    Side effects:
        - Creates `reports_dir` and missing parents if needed.
        - Writes/overwrites `<report_id>.json` on disk.

    Idempotency:
        Idempotent only when input report and target path are identical.
        Repeated calls with different report content overwrite the file.

    Audit Notes:
        - Failure mode: malformed report without `report_id`.
        - Detection: `KeyError` at path construction.
        - Recovery: validate report schema before calling this function.

    Args:
        report: Report payload generated by `build_report`.
        reports_dir: Directory where report files are stored.

    Returns:
        Path: Absolute or relative path to the saved report file.

    Raises:
        KeyError: If `report_id` is missing from `report`.
        OSError: If filesystem operations fail (permissions, disk full).
        TypeError: If report contains non-serializable objects.

    Example:
        >>> p = write_report({"report_id": "abc"}, Path("reports"))
        >>> p.name
        'abc.json'
    """
    reports_dir.mkdir(parents=True, exist_ok=True)
    path = reports_dir / f"{report['report_id']}.json"
    path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    return path
